USE invapp;

-- Drop Tables with Foreign Keys First (in reverse dependency order)
DROP TABLE IF EXISTS DEVIS_DETAILS;
DROP TABLE IF EXISTS DEVIS_HEADER;
DROP TABLE IF EXISTS SELL_INVOICE_DETAILS;
DROP TABLE IF EXISTS SELL_INVOICE_HEADER;
DROP TABLE IF EXISTS BUY_INVOICE_DETAILS;
DROP TABLE IF EXISTS BUY_INVOICE_HEADER;
DROP TABLE IF EXISTS BON_LIVRAISON_ACHAT_DETAILS;
DROP TABLE IF EXISTS BON_LIVRAISON_ACHAT_HEADER;
DROP TABLE IF EXISTS BON_LIVRAISON_VENTE_DETAILS;
DROP TABLE IF EXISTS BON_LIVRAISON_VENTE_HEADER;
DROP TABLE IF EXISTS PRODUCTBL;
DROP TABLE IF EXISTS PRODUCTST;
DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS CATEGORY_BL;
DROP TABLE IF EXISTS CATEGORY_ST;
DROP TABLE IF EXISTS CATEGORY;
DROP TABLE IF EXISTS CLIENT;
DROP TABLE IF EXISTS SUPPLIER;
DROP TABLE IF EXISTS users;

-- Create Category Tables
CREATE TABLE CATEGORY(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    CATEGORYNAME VARCHAR(30) UNIQUE NOT NULL,
    IMAGE LONGBLOB DEFAULT NULL,
    NUMBER_OF_PRODUCTS INTEGER DEFAULT 0
);


-- Insert default categories
INSERT INTO CATEGORY(CATEGORYNAME) VALUES('Uncategorized');


-- Create other tables
CREATE TABLE SUPPLIER(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    SUPPLIERNAME VARCHAR(30) UNIQUE NOT NULL,
    ICE VARCHAR(15) UNIQUE DEFAULT NULL
);

CREATE TABLE CLIENT(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    CLIENTNAME VARCHAR(255) NOT NULL DEFAULT "Client comptoir",
    ICE VARCHAR(15) UNIQUE
);

INSERT INTO CLIENT(CLIENTNAME) VALUES('Client comptoir');


CREATE TABLE PRODUCT(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    REFERENCE VARCHAR(16) UNIQUE NOT NULL,
    PRODUCT_NAME VARCHAR(30) NOT NULL,
    PRICE DECIMAL(10, 2) DEFAULT 0.00,
    QUANTITY INTEGER DEFAULT 0,
    CATEGORY_NAME VARCHAR(30) NOT NULL DEFAULT 'Uncategorized',
    IMAGE LONGBLOB,
    TYPE ENUM('BL', 'Facture', 'Stock') NOT NULL DEFAULT 'Facture',
    FOREIGN KEY (CATEGORY_NAME) REFERENCES CATEGORY(CATEGORYNAME)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);



-- Rest of your tables (invoice, delivery notes, etc.)
CREATE TABLE BUY_INVOICE_HEADER(
    ID_INVOICE INTEGER PRIMARY KEY AUTO_INCREMENT,
    INVOICE_NUMBER VARCHAR(30) UNIQUE NOT NULL,
    SUPPLIER_NAME VARCHAR(30),
    IMAGE LONGBLOB DEFAULT NULL,
    TOTAL_PRICE_TTC DECIMAL(10, 2) DEFAULT 0.00,
    TOTAL_PRICE_HT DECIMAL(10, 2) DEFAULT 0.00,
    TOTAL_PRICE_TVA DECIMAL(10, 2) DEFAULT 0.00,
    DATE DATE DEFAULT CURRENT_DATE,
    FOREIGN KEY (SUPPLIER_NAME) REFERENCES SUPPLIER(SUPPLIERNAME)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE BUY_INVOICE_DETAILS (
    ID_DETAIL INTEGER PRIMARY KEY AUTO_INCREMENT,
    ID_INVOICE INTEGER,
    PRODUCT_ID VARCHAR(16),
    PRODUCT_NAME VARCHAR(30),
    QUANTITY INTEGER,
    UNIT_PRICE_TTC DECIMAL(10, 2),
    TOTAL_PRICE DECIMAL(10, 2),
    FOREIGN KEY (ID_INVOICE) REFERENCES BUY_INVOICE_HEADER(ID_INVOICE)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(REFERENCE)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);

CREATE TABLE SELL_INVOICE_HEADER(
    ID_INVOICE INTEGER PRIMARY KEY AUTO_INCREMENT,
    INVOICE_NUMBER VARCHAR(16) UNIQUE NOT NULL,
    CLIENT_NAME VARCHAR(30),
    COMPANY_ICE VARCHAR(15),
    INVOICE_TYPE VARCHAR(16) DEFAULT 'Personal' NOT NULL,
    TOTAL_PRICE_TTC DECIMAL(10, 2) DEFAULT 0.00,
    TOTAL_PRICE_HT DECIMAL(10, 2) DEFAULT 0.00,
    TVA DECIMAL(10,2) DEFAULT 0.00,
    DATE DATE DEFAULT CURRENT_DATE
);

CREATE TABLE SELL_INVOICE_DETAILS (
    ID_DETAIL INTEGER PRIMARY KEY AUTO_INCREMENT,
    ID_INVOICE INTEGER,
    PRODUCT_ID VARCHAR(16),
    PRODUCT_NAME VARCHAR(30),
    QUANTITY INTEGER,
    UNIT_PRICE_TTC DECIMAL(10, 2) DEFAULT 0.00,
    TOTAL_PRICE_TTC DECIMAL(10, 2) DEFAULT 0.00,
    FOREIGN KEY (ID_INVOICE) REFERENCES SELL_INVOICE_HEADER(ID_INVOICE)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(REFERENCE)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);

CREATE TABLE DEVIS_HEADER(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    DEVIS_NUMBER VARCHAR(16) UNIQUE NOT NULL,
    CLIENT_ID INTEGER,
    CLIENT_NAME VARCHAR(30),
    COMPANY_ICE VARCHAR(15),
    TOTAL_PRICE_TTC DECIMAL(10, 2) DEFAULT 0.00,
    TOTAL_PRICE_HT DECIMAL(10, 2) DEFAULT 0.00,
    TVA DECIMAL(10,2) DEFAULT 0.00,
    DATE DATE DEFAULT CURRENT_DATE,
    FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT(ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE DEVIS_DETAILS (
    ID_DETAIL INTEGER PRIMARY KEY AUTO_INCREMENT,
    ID_DEVIS INTEGER,
    PRODUCT_ID VARCHAR(16),
    QUANTITY INTEGER,
    UNIT_PRICE_TTC DECIMAL(10, 2) DEFAULT 0.00,
    TOTAL_PRICE_TTC DECIMAL(10, 2) DEFAULT 0.00,
    FOREIGN KEY (ID_DEVIS) REFERENCES DEVIS_HEADER(ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(REFERENCE)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);

CREATE TABLE BON_LIVRAISON_ACHAT_HEADER(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    ID_BON VARCHAR(16) UNIQUE NOT NULL,
    SUPPLIER_NAME VARCHAR(30),
    IMAGE LONGBLOB DEFAULT NULL,
    TOTAL_PRICE_TTC DECIMAL(10, 2) DEFAULT 0.00,
    TOTAL_PRICE_HT DECIMAL(10, 2) DEFAULT 0.00,
    TVA DECIMAL(10,2) DEFAULT 0.00,
    DATE DATE DEFAULT CURRENT_DATE,
    FOREIGN KEY (SUPPLIER_NAME) REFERENCES SUPPLIER(SUPPLIERNAME)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE BON_LIVRAISON_ACHAT_DETAILS(
    ID_DETAIL INTEGER PRIMARY KEY AUTO_INCREMENT,
    ID_BON INTEGER,
    PRODUCT_ID VARCHAR(16),
    PRODUCT_NAME VARCHAR(30),
    QUANTITY INTEGER NOT NULL,
    UNIT_PRICE_TTC DECIMAL(10, 2) DEFAULT 0.00,
    TOTAL_PRICE_TTC DECIMAL(10, 2) DEFAULT 0.00,
    FOREIGN KEY (ID_BON) REFERENCES BON_LIVRAISON_ACHAT_HEADER(ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(REFERENCE)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);

CREATE TABLE BON_LIVRAISON_VENTE_HEADER(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    ID_BON VARCHAR(16) UNIQUE NOT NULL,
    ID_COMMANDE INTEGER,
    CLIENT_NAME VARCHAR(30),
    COMPANY_ICE VARCHAR(15),
    INVOICE_TYPE VARCHAR(16) DEFAULT 'Personal' NOT NULL,
    PAYMENT_METHOD VARCHAR(30) NOT NULL DEFAULT 'Cash',
    TOTAL_PRICE_TTC DECIMAL(10, 2) DEFAULT 0.00,
    TOTAL_PRICE_HT DECIMAL(10, 2) DEFAULT 0.00,
    TVA DECIMAL(10,2) DEFAULT 0.00,
    DATE DATE DEFAULT CURRENT_DATE
);

CREATE TABLE BON_LIVRAISON_VENTE_DETAILS(
    ID_DETAIL INTEGER PRIMARY KEY AUTO_INCREMENT,
    ID_BON INTEGER,
    PRODUCT_ID VARCHAR(16),
    PRODUCT_NAME VARCHAR(30),
    QUANTITY INTEGER NOT NULL,
    UNIT_PRICE_TTC DECIMAL(10, 2) DEFAULT 0.00,
    TOTAL_PRICE_TTC DECIMAL(10, 2) DEFAULT 0.00,
    FOREIGN KEY (ID_BON) REFERENCES BON_LIVRAISON_VENTE_HEADER(ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(REFERENCE)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);

CREATE TABLE `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(50) NOT NULL,
  `password` varchar(255) NOT NULL,
  `is_admin` tinyint(1) NOT NULL DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- First, add the type column with a default value
ALTER TABLE PRODUCT 
ADD COLUMN TYPE ENUM('BL', 'Facture', 'Stock') NOT NULL DEFAULT 'Facture';

-- Update existing products to have a type (default is already 'Stock')
-- This is just for demonstration, as the DEFAULT will handle existing rows


CREATE TABLE IF NOT EXISTS APP_SETTINGS (
    SETTING_KEY VARCHAR(50) PRIMARY KEY,
    SETTING_VALUE VARCHAR(255)
);

INSERT INTO APP_SETTINGS (SETTING_KEY, SETTING_VALUE) VALUES 
('MIN_TVA_RATE', '13'),
('MAX_TVA_RATE', '27')
ON DUPLICATE KEY UPDATE SETTING_VALUE = VALUES(SETTING_VALUE);









-- alters:
ALTER TABLE CLIENT MODIFY COLUMN CLIENT_NAME VARCHAR(255);
ALTER TABLE CLIENT ADD COLUMN ADDRESS VARCHAR(255) DEFAULT NULL;
ALTER TABLE SELL_INVOICE_HEADER ADD COLUMN CLIENT_ADDRESS VARCHAR(255) DEFAULT NULL;


ALTER TABLE SELL_INVOICE_HEADER 
ADD COLUMN PAYMENT_TYPE VARCHAR(20) NOT NULL DEFAULT 'espece',
ADD COLUMN PAYMENT_REFERENCE VARCHAR(50) DEFAULT NULL;



-- Table for credit note headers
CREATE TABLE IF NOT EXISTS BUY_CREDIT_NOTE_HEADER (
    ID_CREDIT_NOTE INT AUTO_INCREMENT PRIMARY KEY,
    CREDIT_NOTE_NUMBER VARCHAR(50) NOT NULL UNIQUE,
    SUPPLIER_NAME VARCHAR(100) NOT NULL,
    INVOICE_NUMBER VARCHAR(50) NOT NULL,
    TOTAL_PRICE_TTC DECIMAL(10,2) NOT NULL,
    TOTAL_PRICE_HT DECIMAL(10,2) NOT NULL,
    TOTAL_PRICE_TVA DECIMAL(10,2) NOT NULL,
    DATE DATE NOT NULL,
    IMAGE LONGBLOB,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (SUPPLIER_NAME) REFERENCES SUPPLIER(SUPPLIERNAME)
);

-- Table for credit note details
CREATE TABLE IF NOT EXISTS BUY_CREDIT_NOTE_DETAILS (
    ID_DETAIL INT AUTO_INCREMENT PRIMARY KEY,
    ID_CREDIT_NOTE INT NOT NULL,
    PRODUCT_ID VARCHAR(50) NOT NULL,
    PRODUCT_NAME VARCHAR(100) NOT NULL,
    QUANTITY INT NOT NULL,
    UNIT_PRICE_TTC DECIMAL(10,2) NOT NULL,
    TOTAL_PRICE DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (ID_CREDIT_NOTE) REFERENCES BUY_CREDIT_NOTE_HEADER(ID_CREDIT_NOTE)
);
